#!/bin/sh

HISTSIZE=10000
SAVEHIST=10000
export PATH=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/homebrew/bin
export PATH=$HOME/bin:$PATH


# User Configuration
# export MANPATH="/usr/local/man:$MANPATH"

export CLICOLOR=1
export LSCOLORS=gxExFxdxcxegedabagacad
export EDITOR="vim"
