#!/bin/sh

HISTSIZE=10000
SAVEHIST=10000
export PATH=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/homebrew/bin:/opt/homebrew/Cellar/lazygit/0.34/bin:/Users/libert/miniconda3/bin:/opt/homebrew/opt/libpq/bin:/Users/libert/bin/google-cloud-sdk/bin
export PATH=$HOME/bin:$PATH


# User Configuration
# export MANPATH="/usr/local/man:$MANPATH"

export CLICOLOR=1
export LSCOLORS=gxExFxdxcxegedabagacad
export EDITOR="vim"
export GOOGLE_APPLICATION_CREDENTIALS="/Users/libert/Documents/keys/tully-test-d151a33b7d22.json"
