#!/bin/bash

#   logrm--Logs all file deletion requests unless the -s flag is used.

#removelog="/var/log/remove.log"
archivedir="$HOME/.deleted-files"
copy="$(which cp) -R"

if [ $# -eq 0 ] ; then # if no arguments provided
    #echo "Usage: $0 [-s] list of files or directories" >&2
    echo "rm [-f | -i] [-dIPRrvWx] file ..." >&2
    exit 1
fi

# BEGIN MAIN SCRIPT
# =================

if [ ! -d $archivedir ] ; then
    if [ ! -w $HOME] ; then
        echo "$0 failed: can't create $archivedir in $HOME" >&2
        exit 1
    fi
    mkdir $archivedir
    chmod 700 $archivedir
fi

# backup the file or directory
for arg
do
  newname="$archivedir/$(date "+%d.%m.%H.%M.%S")-$(basename "$arg")"
  if [ -f "$arg" -o -d "$arg" ] ; then
    $copy "$arg" "$newname"
  fi
done

/bin/rm "$@"
exit 0
