#!/bin/bash

# newrm--A replacement for the existing rm command.
# #   This script provides a 
# #   rudimentary unremove capability by creating and utilizing a new 
# #   directory within the user's home directory. It can handle directories
# #   of content as well as individual files. If the user specifies
# #   the -f flag, files are removed and NOT archived.

archivedir="$HOME/.deleted-files"
realrm="$(which rm)"
copy="$(which cp) -R"


if [ $# -eq 0 ] ; then  # let 'rm' output the usage error
  exec $realrm  # our shell is replaced by /bin/rm
fi

# Parse all options looking for '-f'

flags=""

while getopts "dfiPRrvW" opt # flags for rm (d,f,i, etc)
do
  case $opt in
    f ) exec $realrm "$@"     ;;  # exec lets us exit this script directly.
    * ) flags="$flags -$opt"  ;;  # other flags are for 'rm', not us
  esac
done
shift $(( $OPTIND - 1 )) # removes all the options that have been parsed by getopts from the parameters list



# BEGIN MAIN SCRIPT
# =================

if [ ! -d $archivedir ] ; then
    if [ ! -w $HOME] ; then
        echo "$0 failed: can't create $archivedir in $HOME" >&2
        exit 1
    fi
    mkdir $archivedir
    chmod 700 $archivedir
fi

# backup the file or directory
for arg
do
  #newname="$archivedir/$(date "+%S.%M.%H.%d.%m").$(basename "$arg")"
  newname="$archivedir/$(date "+%d.%m.%H.%M.%S")-$(basename "$arg")"
  if [ -f "$arg" -o -d "$arg" ] ; then
    $copy "$arg" "$newname"
  fi
done

exec $realrm $flags "$@"        # our shell is replaced by realrm
