#!/bin/sh

HISTSIZE=10000
SAVEHIST=10000
#export PATH=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/homebrew/bin:/opt/homebrew/Cellar/lazygit/0.34/bin:$HOME/miniconda3/bin:/opt/homebrew/opt/libpq/bin:$HOME/bin/google-cloud-sdk/bin
export PATH=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/homebrew/bin:/opt/homebrew/Cellar/lazygit/0.34/bin:/opt/homebrew/opt/libpq/bin:$HOME/bin/google-cloud-sdk/bin:$HOME/.nix-profile/bin:/run/current-system/sw/bin:/nix/var/nix/profiles/default/bin:/usr/local/bin
export PATH=$HOME/utils/bin:$PATH
export PATH=~/.npm-global/bin:$PATH
export PATH=$HOME/.atuin/bin:$PATH


# User Configuration
# export MANPATH="/usr/local/man:$MANPATH"

export CLICOLOR=1
export LSCOLORS=gxExFxdxcxegedabagacad
export EDITOR="vim"


#aws-vault
export AWS_VAULT_BACKEND="pass"
export AWS_VAULT_PASS_PREFIX=aws-vault
export AWS_VAULT_PASS_PASSWORD_STORE_DIR="$HOME/.password-store"
export AWS_SESSION_TOKEN_TTL=30m
